In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')
df.sample(10)

          brand  km_driven    fuel         owner  selling_price
5391     Maruti      38000  Petrol  Second Owner         350000
5604    Hyundai     148000  Diesel  Second Owner         350000
6553       Ford      93500  Diesel  Second Owner         350000
4793     Toyota       9654  Petrol   First Owner         894999
2602    Hyundai      70000  Petrol   First Owner         330000
4714     Maruti     139000  Diesel   First Owner         620000
5014     Maruti     100000  Petrol   Third Owner         450000
5347    Hyundai     120000  Diesel  Second Owner         195000
2951     Maruti     170000  Diesel   First Owner         355000
4892  Chevrolet     100000  Petrol   Third Owner          65000

In [3]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [4]:
df.shape

(8128, 5)

USING PANDAS

In [11]:
# as we have a lot of brands, we will use one hot encoding only on fuel type and owner type.
pd.get_dummies(df,columns=['fuel','owner'],dtype=int,drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

using scikit learn

In [12]:
df.shape

(8128, 5)

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [16]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
ohe = OneHotEncoder(drop = 'first')

In [36]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [30]:
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [31]:
X_train_new

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]], shape=(6502, 7))

In [32]:
X_train[['brand','owner']].values

array([['Tata', 'First Owner'],
       ['Honda', 'Second Owner'],
       ['Hyundai', 'Fourth & Above Owner'],
       ...,
       ['Hyundai', 'First Owner'],
       ['Maruti', 'First Owner'],
       ['Maruti', 'Second Owner']], shape=(6502, 2), dtype=object)

In [34]:
np.hstack((X_train[['brand','owner']].values,X_train_new)).shape

(6502, 9)